__title__ = 'dhis2.py'
__description__ = 'Python wrapper for DHIS2'
__url__ = 'https://github.com/davidhuser/dhis2.py'
__version__ = '1.5.3'
__author__ = 'David Huser'
__author_email__ = 'dhuser@baosystems.com'
__license__ = 'MIT'
