__title__ = 'dhis2.py'
__description__ = 'Minimalistic wrapper around the DHIS2 API'
__url__ = 'https://github.com/davidhuser/dhis2.py'
__version__ = '0.29.14'
__author__ = 'David Huser'
__author_email__ = 'dhuser@baosystems.com'
__license__ = 'MIT'
