__title__ = 'dhis2.py'
__description__ = 'DHIS2 API Wrapper for Python'
__url__ = 'https://github.com/davidhuser/dhis2.py'
__version__ = '0.29.0'
__author__ = 'David Huser'
__author_email__ = 'dhuser@baosystems.com'
__license__ = 'MIT'
